---
title: "STA302_Project"
output: html_document
date: "2026-05-18"
---

# Data cleaning
```{r}
data <- read.csv("data/FinalProject_dataset.csv")
dim(data)
names(data)
str(data)

data_subset <- data[, c(
  "CURRENT.BUILDING.EVAL.SCORE",
  "PROPERTY.TYPE",
  "YEAR.BUILT",
  "CONFIRMED.UNITS",
  "CONFIRMED.STOREYS",
  "BUILDING.CLEANLINESS",
  "BUILDING.EXTERIOR",
  "COMMON.AREA.PESTS"
)]
summary(data_subset)
str(data_subset)

data_subset[data_subset == "N/A"] <- NA
clean_data <- na.omit(data_subset)
dim(clean_data)

clean_data$PROPERTY.TYPE <- as.factor(clean_data$PROPERTY.TYPE)
clean_data$BUILDING.EXTERIOR <- as.numeric(clean_data$BUILDING.EXTERIOR)
str(clean_data)
```

```{r}

# FinalProject_dataset
write.csv(clean_data,
          "output/cleaned_apartment_building_data.csv",
          row.names = FALSE)


# Linear Regression Model
model <- lm( CURRENT.BUILDING.EVAL.SCORE ~ PROPERTY.TYPE + YEAR.BUILT +
    CONFIRMED.UNITS + CONFIRMED.STOREYS + BUILDING.CLEANLINESS + 
    BUILDING.EXTERIOR + COMMON.AREA.PESTS,
  data = clean_data )

summary(model)

confint(model)


par(mfrow = c(1, 3))

#Residual vs fitted 
plot(model, which = 1) 

#QQ plot
plot(model, which = 2) 

#Standardized residual vs fitted
plot(fitted(model),
     rstandard(model),
     main = "Standardized Residual vs Fitted",
     xlab = "Fitted values",
     ylab = "Standardized residuals")

abline(h = 0, col = "red")

par(mfrow = c(1, 1))

hist(
  rstandard(model),
  main = "Histogram of Standardized Residuals",
  xlab = "Standardized Residuals",
  col = "lightgray",
  border = "white"
)


numeric_vars <- clean_data[, c(
  "YEAR.BUILT",
  "CONFIRMED.UNITS",
  "CONFIRMED.STOREYS",
  "BUILDING.CLEANLINESS",
  "BUILDING.EXTERIOR"
)]

```

